kind: Deployment
apiVersion: apps/v1
metadata:
  name: front-my-v1
  labels:
    app: front-my
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-my
      version: v1
  template:
    metadata:
      labels:
        app: front-my
        version: v1
    spec:
      containers:
        - name: front-my
          image: git.dorsa.cloud:5050/cloud-computing/core/front-my-core/front-my-stage:latest
          ports:
            - name: http-0
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: dorsa-git