workflow:
  # This specifies the valid branches for this workflow
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

stages:
  - package
  - deploy

variables:
  KUBE_CONTEXT: dorsacloud/frontend/dorsa-portal:portal-front-agent


## Stage 1 : PACKAGE

package_main:
  stage: package
  tags: [main-gitlab-runner]
  script:
    - docker build -t $DOCKER_REGISTRY/front-portal-main:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-portal-main:latest .
    - docker push $DOCKER_REGISTRY/front-portal-main:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/front-portal-main:latest

# Stage 2 : DEPLOY

deploy_admin_main:
  stage: deploy
  tags: [main-gitlab-runner]
  needs: [package_main]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl -n stage apply -f $CI_PROJECT_DIR/deployments/.
    - kubectl -n stage rollout restart deployment portal-front-v1
