workflow:
  ## This specifies the valid branches for this workflow
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "raahbar" || $CI_COMMIT_BRANCH == "bahar"'
      when: always
    - when: never

default:
  tags: 
    - main-gitlab-runner

stages:
  - package
  - deploy

variables:
  KUBE_CONTEXT_BAHARTEL: cloud-computing/dorsa/front-my-core:bahartel-front-my
  DOCKER_REGISTRY: git.dorsa.cloud:5050/cloud-computing/dorsa/front-my-core

# ----### Bahar ###----

package_bahartel_prod:
  stage: package
  script:
    - docker build -f Dockerfile.bahartel.production -t $DOCKER_REGISTRY/front-client-bahartel:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-client-bahartel:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-client-bahartel
  only:
    - bahar

deploy_bahartel_prod:
  stage: deploy
  needs: [package_bahartel_prod]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_BAHARTEL
    - kubectl -n production apply -f $CI_PROJECT_DIR/deployments/front-client-bahartel.yaml
    - kubectl -n production rollout restart deployment front-ver2-client
  when: on_success
  only: 
    - bahar