workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "development"'
      when: always
    - when: never

default:
  tags: 
    - frontend

stages:
  - package
  - deploy

variables:
  KUBE_CONTEXT_DORSA: cloud-computing/dorsa/front-my-core:dorsa-front-my
  KUBE_CONTEXT_BAHARTEL: cloud-computing/dorsa/front-my-core:bahartel-front-my
  KUBE_CONTEXT_NETRANO: cloud-computing/dorsa/front-my-core:netrano-front-client
  DOCKER_REGISTRY: git.dorsa.cloud:5050/cloud-computing/dorsa/front-my-core

# development

package_development:
  stage: package
  script:
    - docker build -f Dockerfile.stage -t $DOCKER_REGISTRY/front-client-stage:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-client-stage:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-client-stage
  only:
    - development

deploy_development:
  stage: deploy
  needs: [package_development]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_DORSA
    - kubectl -n development apply -f $CI_PROJECT_DIR/deployments/front-client-stage.yaml
    - kubectl -n development rollout restart deployment front-client-stage
  only:
    - development

# ---- *** dorsa master ***---

package_dorsa_master:
  stage: package
  script:
    - docker build -f Dockerfile.dorsa -t $DOCKER_REGISTRY/front-client:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-client:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-client
  only:
    - master

deploy_dorsa_master:
  stage: deploy
  needs: [package_dorsa_master]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_DORSA
    - kubectl -n production apply -f $CI_PROJECT_DIR/deployments/front-client-dorsa.yaml
    - kubectl -n production rollout restart deployment front-ver2-client
  when: manual
  only:
    - master

# ---- *** bahar master ***---

package_bahartel_master:
  stage: package
  script:
    - docker build -f Dockerfile.dorsa -t $DOCKER_REGISTRY/front-client-bahartel:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-client-bahartel:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-client-bahartel
  only:
    - master

deploy_bahartel_master:
  stage: deploy
  needs: [package_bahartel_master]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_BAHARTEL
    - kubectl -n production apply -f $CI_PROJECT_DIR/deployments/front-client-bahartel.yaml
    - kubectl -n production rollout restart deployment front-ver2-client
  when: manual
  only:
    - master


# ---- *** netrano master ***---

package_netrano_master:
  stage: package
  script:
    - docker build -f Dockerfile.netrano -t $DOCKER_REGISTRY/front-client-netrano:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-client-netrano:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-client-netrano
  only:
    - master

deploy_netrano_master:
  stage: deploy
  needs: [package_netrano_master]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_NETRANO
    - kubectl -n production apply -f $CI_PROJECT_DIR/deployments/front-client-netrano.yaml
    - kubectl -n production rollout restart deployment front-ver2-client
  when: manual
  only:
    - master