workflow:
  # This specifies the valid branches for this workflow
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "raahbar" || $CI_COMMIT_BRANCH == "bahar"'
      when: always
    - when: never

default:
  tags: 
    - main-gitlab-runner

stages:
  - package
  - deploy

variables:
  KUBE_CONTEXT_DORSA: cloud-computing/dorsa/front-my-core:dorsa-front-my
  KUBE_CONTEXT_BAHARTEL: cloud-computing/dorsa/front-my-core:bahartel-front-my
  DOCKER_REGISTRY: git.dorsa.cloud:5050/cloud-computing/dorsa/front-my-core

## development

package_development:
  stage: package
  script:
    - docker build -f Dockerfile.development -t $DOCKER_REGISTRY/front-client-development:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-client-development:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-client-development
  only:
    - development

deploy_development:
  stage: deploy
  needs: [package_development]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_DORSA
    - kubectl -n development apply -f $CI_PROJECT_DIR/deployments/front-client-development.yaml
    - kubectl -n development rollout restart deployment front-client-development
  only:
    - development

# ---- *** Dorsa master ***---

package_dorsa_master:
  stage: package
  script:
    - docker build -f Dockerfile.dorsa.production -t $DOCKER_REGISTRY/front-client:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-client:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-client
  when: manual
  only:
    - master

deploy_dorsa_master:
  stage: deploy
  needs: [package_dorsa_master]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_DORSA
    - kubectl -n production apply -f $CI_PROJECT_DIR/deployments/front-client-dorsa.yaml
    - kubectl -n production rollout restart deployment front-ver2-client
  when: on_success
  only: 
    - master

# ----### Bahar ###----

package_bahartel_prod:
  stage: package
  script:
    - docker build -f Dockerfile.bahartel.production -t $DOCKER_REGISTRY/front-my-bahartel:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-my-bahartel:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-my-bahartel
  when: manual
  only:
    - bahar

deploy_bahartel_prod:
  stage: deploy
  needs: [package_bahartel_prod]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_BAHARTEL
    - kubectl -n production apply -f $CI_PROJECT_DIR/deployments/front-client-bahartel.yaml
    - kubectl -n production rollout restart deployment front-my-v1
  when: on_success
  only: 
    - bahar

# ----*** Dorsa main ***----

package_dorsa_prod:
  stage: package
  script:
    - docker build -f Dockerfile.dorsa.production -t $DOCKER_REGISTRY/front-my-dorsa-main:$CI_PIPELINE_ID -t $DOCKER_REGISTRY/front-my-dorsa-main:latest .
    - docker push --all-tags $DOCKER_REGISTRY/front-my-dorsa-main
  when: manual
  only:
    - main

deploy_dorsa_prod:
  stage: deploy
  needs: [package_dorsa_prod]
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT_DORSA
    - kubectl -n main apply -f $CI_PROJECT_DIR/deployments/front-my-dorsa.yaml
    - kubectl -n main rollout restart deployment front-my-v1
  when: on_success
  only: 
    - main
