# Stage 1
#FROM node:18-bullseye-slim AS builder
FROM nexus.dorsa.cloud/library/node:22-bullseye-slim AS builder
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install 
COPY . .

ENV REACT_APP_PRODUCTION_URL_V1="https://my.baharcloud.com"

# Build the application
RUN yarn run build
# Stage 2
#FROM nginx:1.25-alpine
FROM nexus.dorsa.cloud/library/nginx:1.25-alpine

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
