# ---- Stage 1: Build React App ----
FROM nexus.dorsa.cloud/library/node:22-bullseye-slim AS builder
WORKDIR /app

# Copy only the files needed to install dependencies first
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the source code
COPY . .

# Set environment variables needed at build time
ENV REACT_APP_PRODUCTION_URL_V1="https://my.baharcloud.com"

# Build the React app
RUN yarn build

# ---- Stage 2: Serve via Nginx ----
FROM nexus.dorsa.cloud/library/nginx:1.25-alpine

WORKDIR /usr/share/nginx/html

# Copy built files from builder stage
COPY --from=builder /app/build /usr/share/nginx/html

# Remove default Nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d

# Expose HTTP port
EXPOSE 80

# Start Nginx in foreground
ENTRYPOINT ["nginx", "-g", "daemon off;"]
    