# Stage 1
#FROM node
FROM nexus.dorsa.cloud/library/node:22-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json* ./
# Install dependencies
RUN yarn install 

# Copy the rest of the application code
COPY . .

# Build the application
RUN yarn run build

# Stage 2
#FROM nginx:1.25-alpine
FROM nexus.dorsa.cloud/library/nginx:1.25-alpine

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
